### ISSUE TITLE
Has a dependency on the `fs` npm package, which does nothing?

### ISSUE THREAD

**Issue by s100** [IBM/message-catalog-manager#29]
What is the reason for this?

https://github.com/IBM/message-catalog-manager/blob/7fb7ae63547439b96782b4be72fe3b7d92469c37/package.json#L22

This package (1) does nothing but log "I'm \`fs\` modules" to the console and (2) does not appear to be in use by this package. I highly recommend removing it.

**Comment by mattbaileyuk** [comment]
Good spot - I don't know why it was there in the first place. I took over this repo in the summer to get a new version published without the Node engine warnings, but haven't had a chance yet to look over things like the dependencies and their versions.
